### ISSUE TITLE
Getting Started by getting familiar with Git & GitHub

### ISSUE THREAD

**Issue by Ahmed-Ayman** [Ahmed-Ayman/NoAltShift#1]
https://www.udacity.com/course/how-to-use-git-and-github--ud775?autoenroll=true#_=_

**Comment by MahmoudZareef** [comment]
Take the highlighted text as input

**Comment by MahmoudZareef** [comment]
process text from English to Arabic (until now )

**Comment by MahmoudZareef** [comment]
use right click and /or shortcut to change text

**Comment by MahmoudZareef** [comment]
add from Arabic to English support

**Comment by MahmoudZareef** [comment]
add other languages support
